### ISSUE TITLE
Specific configs for storybook

### ISSUE THREAD

**Issue by himynameisjonas** [storybookjs/ember-cli-storybook#10]
Is it possible to add a hook to be able to modify the parsed config before generating the preview_head.html file?
I would for example like to be able to enable ember-cli-mirage when using storybook, without enabling it in the regular development environment.

**Comment by billpull** [comment]
At least in the above example you could try setting your enabled mirage value w/ an environment var and set that via the `scripts` for when running storybook.

`'ember-cli-mirage': { enabled: process.env.ENABLE_MIRAGE }`
```
{
  "scripts": {
    "build-storybook": "ENABLE_MIRAGE=true ember build && build-storybook -p 9001 -s dist",
    "storybook": "ENABLE_MIRAGE=true ember serve & start-storybook -p 9001 -s dist"
  }
}
```

would be nice to potentially have storybook specific config but seems odd to me for it to reconfigure other addon hooks.

**Comment by gabrielcsapo** [comment]
@billpull what would this specific config look like?

**Comment by billpull** [comment]
I believe what I was referring to was how Ember allows you to specify a configuration object that then can be referenced throughout the app.

https://guides.emberjs.com/release/configuring-ember/

The default one is under `/config/environment.js` and some other addons, such as ember-cli-deploy, provide additional config files ex: `/config/deploy.js`. The Storybook addon could check for the existence of `/config/storybook.js` for ember specific changes. 

Looking at my answer above that seems like its likely overkill unless there are many ember specific hooks to configure.

**Comment by gabrielcsapo** [comment]
Thanks for the context @billpull ! I agree I don't think there are many things that will need custom configuration and therefore think we can close this out until a time comes where we have a ton of customizations (if a time comes).
