### ISSUE TITLE
release 0.5.0

### ISSUE THREAD

**Issue by gabrielcsapo** [storybookjs/ember-cli-storybook#100]
I released and updated everything https://github.com/storybookjs/ember-cli-storybook/pull/99

**Comment by gabrielcsapo** [comment]
@dbendaou would you be able to help with releasing this?

**Comment by dbendaou** [comment]
Seems ok? I can see the release here https://github.com/storybookjs/ember-cli-storybook/releases/tag/0.5.0

**Comment by nlfurniss** [comment]
> Seems ok? I can see the release here https://github.com/storybookjs/ember-cli-storybook/releases/tag/0.5.0

It's not released [on NPM](https://www.npmjs.com/package/@storybook/ember-cli-storybook)

**Comment by gabrielcsapo** [comment]
Yes it was never released to npm @dbendaou

**Comment by dbendaou** [comment]
I don't have the right to do so, I'm not part of the NPM org, could you help here to release it to NPM @shilman ?

**Comment by shilman** [comment]
@dbendaou @gabrielcsapo published. sorry I missed the notification earlier!
