### ISSUE TITLE
'@storybook/ember-cli-storybook@latest' is not in the npm registry

### ISSUE THREAD

**Issue by stormwarning** [storybookjs/ember-cli-storybook#11]
It looks like the `name` in `package.json` was updated, but maybe it hasn't been published to npm under the new name yet? Or maybe the access wasn't explicitly [made public](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages#publishing-scoped-public-packages) (scoped packages are private by default).

Side note: `ember install ember-cli-storybook` seems to add the appropriate packages, but exits with this error:

```
The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.
```

**Comment by backspace** [comment]
Is there a workaround for this? 😞

**Comment by joegaudet** [comment]
Seeing the same problem here.

**Comment by gabrielcsapo** [comment]
Let me publish, should be up in a couple hours. I will report back when it
is done.

**Comment by joegaudet** [comment]
Any news on this? Looking to kick off a project this week that would involve this plugin.

**Comment by gabrielcsapo** [comment]
```
npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@storybook%2fember-cli-storybook - You must sign up for private packages

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gabrielcsapo/.npm/_logs/2019-08-29T05_03_24_073Z-debug.log
```

@shilman I am not a part of the npm org. Would you be able to publish this.

**Comment by shilman** [comment]
@gabrielcsapo I'm happy to, but I'm a big confused.

First error:

```
MMBP15:ember-cli-storybook shilman$ yarn build
yarn run v1.16.0
$ ember build
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
⠋ BuildingYour names in package.json and index.js should match. The addon in /Users/shilman/projects/storybookjs/ember-cli-storybook currently have '@storybook/ember-cli-storybook' in package.json and 'ember-cli-storybook' in index.js.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Fixed by modifying index.js & re-attempted:
```
MMBP15:ember-cli-storybook shilman$ yarn build
yarn run v1.16.0
$ ember build
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Environment: development
Generating files needed by Storybook
Parsing /var/folders/nc/f_jb0zxj45ng66263ycdg3_80000gp/T/broccoli-17154VyRIBbZCf7Bu/out-160-broccoli_merge_trees/tests/index.html
Generating preview-head.html
Generating files needed by Storybook
cleaning up...
ENOENT: no such file or directory, open '/Users/shilman/projects/storybookjs/ember-cli-storybook/.storybook/preview-head.html'
```

I don't know anything about ember, but I'm assuming I need to build before I publish.

**Comment by joegaudet** [comment]
@shilman That looks like you're building the in addon app/

**Comment by gabrielcsapo** [comment]
Yes. You don’t need to build this before you publish. It acts as a part of
the build step for the project bringing it in. The app currently in this
project is used as testing fixture to make sure the build steps work
correctly.

**Comment by shilman** [comment]
OK, published as is as `@storybook/ember-cli-storybook@0.1.0`. LMK how that looks. And @gabrielcsapo let's figure out how to get you publishing rights.

**Comment by gabrielcsapo** [comment]
@shilman sounds good! I haven't been able to commit a lot of time to supporting storybook. My apologies. I had support to bring this into work, but that has tapered and I am trying to find ways of using this at LinkedIn.

**Comment by joegaudet** [comment]
@shilman @gabrielcsapo still having the same issue when I run:

```ember install ember-cli-storybook```

```
Yarn: Installed ember-cli-storybook
installing ember-cli-storybook
The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.
```
