### ISSUE TITLE
The `ember generate <entity-name>` command requires an entity name to be specified.

### ISSUE THREAD

**Issue by stormwarning** [storybookjs/ember-cli-storybook#12]
Running `ember install ember-cli-storybook` seems to add the appropriate packages, but exits with the above error.

Looking at [the blueprint](https://github.com/storybookjs/ember-cli-storybook/blob/master/blueprints/ember-cli-storybook/index.js) it looks like `@storybook/ember` is added to `package.json`, but fails before `@babel/core` or `babel-loader` are installed.

**Comment by joegaudet** [comment]
Still seeing this issue after https://github.com/storybookjs/ember-cli-storybook/issues/11 was seolved.

**Comment by backspace** [comment]
Does anyone have a workaround? 😢

**Comment by backspace** [comment]
`ember install @storybook/ember-cli-storybook` lets me install it at least! After that the application won’t start but I’m not sure what that’s about yet.

**Comment by gossi** [comment]
There is a fix in #27 

For now do the following:

Install: `ember install @storybook/ember-cli-storybook`

After Install: `ember g ember-cli-storybook`

The second command will add required packages plus does the bootstrapping.

**Comment by teakap** [comment]
> ember g ember-cli-storybook

This command still returns the same error for me.

**Comment by meirish** [comment]
Try `ember g ember-cli-storybook default` to get the needed files

**Comment by fpauser** [comment]
I think this bug should be reopened as it seems not to be fixed.

Steps to reproduce:
```bash
ember addon addon-storybook-test && cd addon-storybook-test && ember install ember-cli-storybook
```

Error output:
```bash
🚧  Installing packages... This might take a couple of minutes.
Yarn: Installed @storybook/ember-cli-storybook
installing ember-cli-storybook
The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.
```

**Comment by gabrielcsapo** [comment]
re-opening this until it is fixed

**Comment by gabrielcsapo** [comment]
This should fix this issue https://github.com/storybookjs/ember-cli-storybook/pull/57
