### ISSUE TITLE
runningTests = true; Should come after vendor not before.

### ISSUE THREAD

**Issue by arthur5005** [storybookjs/ember-cli-storybook#16]
https://github.com/storybookjs/ember-cli-storybook/blob/4b3cc72dc83bc238b6df2b6e55c7f771cf7f6050/util.js#L126-L129

I'm on Ember 3.13 and I'm not sure if it's as a result of being on the latest version, but Ember builds `vendor.js` by setting `runningTests=false` as one of its first lines. 

<img width="451" alt="Screen Shot 2019-10-17 at 4 23 27 PM" src="https://user-images.githubusercontent.com/697846/67054811-97c0dc80-f0fa-11e9-80bc-7d530c78eceb.png">

The application attachment and the check for this global variable doesn't come until the very end of `app-name.js`, which comes later. 

So as far as I can tell, this variable should be set _in between_ `vendor.js` and `app-name.js`.

An aside: Is there anyway to prevent storybook calling generatePreviewHead when I start it up?

**Comment by meirish** [comment]
closed by https://github.com/storybookjs/ember-cli-storybook/pull/17
