### ISSUE TITLE
More options to configure the app running in storybook

### ISSUE THREAD

**Issue by gossi** [storybookjs/ember-cli-storybook#21]
I've been playing around with storybook and ember and it's very nice.

What I realized, there is little to no configuration been able to do for the app that is loaded within storybook. E.g. it is loading an app as it was 2 years ago, e.g. with the application wrapper element.

What I'd like to do:

- More configuration options as we have nowadays (e.g. optional-features)
- An application route that I can modify 🙈 (I'm loading my theme in the application route, in storybook my components don't have a theme and are black and white)
- Maybe even have a sample app, that is mounted in storybook. If I do run storybook, it's the dummy app inside storybook, but if I go to `localhost:4200` it looks different.

The sample app could be located at `.storybook/app` and is _allowed_ to only have an application route that is loaded from storybook.

What do you think? If there is an agreement, I will also find time to help implement :)

**Comment by gabrielcsapo** [comment]
I think this would be great. As ember continues to move to a commonjs model where we can bundle without the need to build two applications this should become easier. For the time being this is the model we have to work within.
