### ISSUE TITLE
app name that starts with `test` will not include the app js in preview-head.html

### ISSUE THREAD

**Issue by meirish** [storybookjs/ember-cli-storybook#26]
I ran into this when trying out https://github.com/meirish/test-storybook

**Comment by gabrielcsapo** [comment]
<img width="1680" alt="Screen Shot 2021-04-09 at 6 34 53 PM" src="https://user-images.githubusercontent.com/1854811/114254095-48134800-9962-11eb-82d7-6ed865ee33bd.png">

I was able to serve the example repo when I bumped everything to the latest. Please comment if you have any issues with this.
