### ISSUE TITLE
Upgrade deprecated version of ember-cli-inject-live-reload

### ISSUE THREAD

**Issue by brianhjelle** [storybookjs/ember-cli-storybook#28]
I am getting a deprecation warning that says "Upgrade ember-cli-inject-live-reload version to 1.10.0 or above". I'm using Ember 3.14.

**Comment by btecu** [comment]
@brianhjelle this issue is related to `ember-cli`. You should chime in there:
https://github.com/ember-cli/ember-cli/issues/8391

**Comment by dbendaou** [comment]
This as been fixed in the last version of storybook ! You can close then :)

**Comment by gabrielcsapo** [comment]
Closing as this issue is being tracked in ember-cli.
