### ISSUE TITLE
Livereload URL in preview-head.html returns 404

### ISSUE THREAD

**Issue by ddoria921** [storybookjs/ember-cli-storybook#31]
The livereload URL generated in the `preview-head.html` file is trying to perform a GET at
```
http://localhost:7020/_lr/livereload.js?port=7020&host=localhost
```
but that returns a 404.

<img width="1366" alt="Screen Shot 2020-02-04 at 3 56 43 PM" src="https://user-images.githubusercontent.com/3970871/73786351-1489cc00-4767-11ea-8055-7a3e0978d331.png">

When I load up the ember app locally I noticed that the livereload URL that it is using is
```
http://localhost:7020/livereload.js?port=7020&host=localhost
``` 
Notice it doesn't use `_lr/` in the URL . I went ahead and changed `preview-head.html` manually to use the same URL that the ember app uses for livereload and it worked. 

I also noticed that it's been hardcoded this way from the beginning. Any reason this addon is hardcoded to include `_lr/` in the livereload URL? Is this breaking any other storybook + ember setups?

**Comment by gabrielcsapo** [comment]
What version of ember and ember-cli are you using?

**Comment by ddoria921** [comment]
ember: 3.1.0
ember-cli: 3.1.4

**Comment by gabrielcsapo** [comment]
@ddoria921 have you tried bumping to ember-cli@latest? You don't have to bump ember-source just ember-cli. This should use the correct version of live reload and the endpoint that it expects.

**Comment by ddoria921** [comment]
oh interesting. Let me try that and I'll get back to you
