### ISSUE TITLE
How to add custom head tags?

### ISSUE THREAD

**Issue by arjenblokzijl** [storybookjs/ember-cli-storybook#38]
Hi,

I was wondering how to add custom head tags like typescript or other external files. The documentation of Storybook points to [this page](https://storybook.js.org/docs/configurations/add-custom-head-tags/) and suggest to add these to the `preview-head.html` file. That will only work until ember-cli-storybook regenerates the file. Any pointers how to solve this issue?

Thanks in advance!

**Comment by brunomacf** [comment]
I'm stuck with this as well... @arjenblokzijl have you found a solution? I want to add a tag importing some custom font!!

**Comment by brunomacf** [comment]
@arjenblokzijl i think i found a way at least if you are working on an addon... in your `index.js` you can do:

```js
/* eslint-disable */

'use strict';

module.exports = {
  name: require('./package').name,
  included: function(/* app */) {
    this._super.included.apply(this, arguments);
  },
  contentFor(type) {
    if (type === 'my-addon') {
      return [
        '<link rel="stylesheet" type="text/css" href="...">'
      ].join('\n');
    }
  }
};
```

and then in your `tests/index.html` you can add:

```hbs
<!DOCTYPE html>
<html>
  <head>
    ...
    {{content-for "my-addon"}}
    ...
  </head>
  ...
</html>
```

seems to work

**Comment by arjenblokzijl** [comment]
@brunomacf I pulled a quick and dirty trick in our build process: `sed -i.bak "s#</head>#<link rel="stylesheet" href="https://use.typekit.net/XXXX.css" /></head>#" ./storybook-static/iframe.html`. Not really pretty, but it's working for us and the client can review the components in Storybook.

**Comment by gabrielcsapo** [comment]
We should be able to add this to a config option. It is a result of whatever your test index.html output is, but there is no reason we couldn't also append more information that will not be added.
