### ISSUE TITLE
Constant Churn with preview-head.hbs

### ISSUE THREAD

**Issue by jherdman** [storybookjs/ember-cli-storybook#39]
It seems like the `<meta name="your-app/config/environment"` tag in `preview-head.hbs` is constantly changing. Normally we don't see these changes because they're injected at runtime, whereas this harness seems to be hard coding them. Some questions:

* Why is that?
* Can we ignore these changes?

**Comment by jelhan** [comment]
Wondering if `storeConfigInMeta` build-time configuration may help. It controls if Ember CLI puts the configuration in the meta tag or includes it in generated JavaScript. It's not very well documented. I only found it in [old Ember CLI docs on ember-cli.com](https://ember-cli.com/user-guide/#application-configuration) but I think it's still supported.

**Comment by gabrielcsapo** [comment]
This is a result of how we load the ember app that backs storybooks ability to render components. As ember progresses we will not need to load the entire application and this will potentially not be needed as a result. As of right now preview-head will continue to update whenever the application config does.
