### ISSUE TITLE
Make imports from `ember-cli-htmlbars-inline-precompile` work

### ISSUE THREAD

**Issue by techdragon** [storybookjs/ember-cli-storybook#4]
The package `ember-cli-htmlbars-inline-precompile` updated to support using the proper package name (eg `import hbs from 'ember-cli-htmlbars-inline-precompile'`) in addition to the existing `import hbs from 'htmlbars-inline-precompile'` but this package seems to break that. I've updated the package to 2.1.0 and when using `hbs` inside a story file, I get a lot of errors, mostly to do with `Module not found: Error: Can't resolve 'fs'` and storybook stops working.

**Comment by iamareebjamal** [comment]
Facing this issue. Any solutions?

**Comment by gabrielcsapo** [comment]
@iamareebjamal since this is compiled into the browser, how does this work on your project locally? the browser will throw a similar error for process not being defined

**Comment by iamareebjamal** [comment]
`import { hbs } from 'ember-cli-htmlbars'` is not used in the project anywhere except tests. I am sure there is some config issue on my part but can't figure out what's different in my config and the example repo (which is working correctly). Maybe I'm using fastboot, that's why? Not sure

**Comment by iamareebjamal** [comment]
Even when I manually patch the dependency, it stops throwing that error but starts throwing `Object(...) is not a function` where I define my stories

**Comment by gabrielcsapo** [comment]
Would you be able to post of example of what your stories look like? That error seems like it is an issue with the format of the stories.

**Comment by iamareebjamal** [comment]
PR is mentioned here - https://github.com/storybookjs/ember-cli-storybook/issues/35
https://github.com/fossasia/open-event-frontend/pull/4325

**Comment by gabrielcsapo** [comment]
I am looking at your project now it looks like there are some misconfigurations one being 

```
[ember-cli-dotenv]: ENOENT: no such file or directory, open '/Users/gabrielcsapo/Documents/contributions/open-event-frontend/.env'
```

**Comment by gabrielcsapo** [comment]
I will get it working and push a PR to your fork

**Comment by iamareebjamal** [comment]
That can just be fixed by `cp .env.example .env`. We have put .env in .gitignore. I don't think that's the problem

**Comment by gabrielcsapo** [comment]
Okay, will look into where that is done, but it looks like a simple yarn start will not be able to get it working

**Comment by iamareebjamal** [comment]
Yes, it is a manual one time step.

**Comment by iamareebjamal** [comment]
I got to the actual problem. It gets transpiled to 
```js
var ToStorybook = function ToStorybook() {
  return {
    template: Object(ember_cli_htmlbars__WEBPACK_IMPORTED_MODULE_3__["hbs"])(_templateObject()),
    context: {
      onClick: Object(_storybook_addon_links__WEBPACK_IMPORTED_MODULE_4__["linkTo"])('Button')
    }
  };
};
```

`ember_cli_htmlbars__WEBPACK_IMPORTED_MODULE_3__` has no entry for 'hbs' and hence it turns to `Object(undefined)` which then throws `Object is not a function`. Wasn't super easy to debug because of webpack source maps throwing me back at source code again and again. Any idea what might be causing this?

**Comment by gabrielcsapo** [comment]
@iamareebjamal is this still an issue?

**Comment by iamareebjamal** [comment]
Will check and report. It's quite a daunting task

**Comment by iamareebjamal** [comment]
Working now

**Comment by dbendaou** [comment]
Ok so I guess we can close it? Can you confirm @techdragon?
