### ISSUE TITLE
How to handle/mock dynamic segment

### ISSUE THREAD

**Issue by emattias** [storybookjs/ember-cli-storybook#46]
I have a component that outputs `link-to` component the links to a route that requires a model that is loaded from a parent routes dynamic segment.

I get this error:

> You attempted to generate a link for the "jobs.job.activity.candidate" route, but did not pass the models required for generating its dynamic segments. You must provide param `company_id` to `generate`.

Can I set a dynamic segment programatically or mock them so that the `link-to` will find the company model in storybook, like it does in the app (by the root route)

I am using [this solution](https://github.com/storybookjs/ember-cli-storybook#components-that-need-routing-for-query-parameters) for accessing routing information at all.

**Comment by dbendaou** [comment]
If the parent component rely on a `company` model you can create them in the `Ember store` and it should be able to find them just as in the application. 
You can have a look at https://github.com/storybookjs/ember-cli-storybook#working-with-store, in your case you won't need to pass the model to the component as the parent will retrieve it. 
Let me know if that fix your issue

**Comment by gabrielcsapo** [comment]
Closing as a fix was provided, if you have any more issues please let us know!
