### ISSUE TITLE
`ember-cli-storybook` config key was removed in v0.3.0

### ISSUE THREAD

**Issue by BarryThePenguin** [storybookjs/ember-cli-storybook#52]
### Describe the bug

The config key for this addon was changed in https://github.com/storybookjs/ember-cli-storybook/pull/50/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L11-R11,
from `ember-cli-storybook` to the name of this package (`@storybook/ember-cli-storybook`)

Instead of breaking everyone, we could reinstate the old key and print a deprecation message instead.
We'll want to update any documentation too..

### Additional context

See https://github.com/storybookjs/storybook/pull/13429#issuecomment-751645907

**Comment by dbendaou** [comment]
Do you feel to make the appropriate PR to fix the issue with `@storybook/ember-cli-storybook` ? 
As many user that use the doc integration and rely on the generated file will fail the build :/

**Comment by BarryThePenguin** [comment]
Yup, I've got a PR in progress but got distracted 😅 I'll aim to have something up soon
