### ISSUE TITLE
Adding basics tests

### ISSUE THREAD

**Issue by dbendaou** [storybookjs/ember-cli-storybook#58]
In order to ease contribution and be more confident to merge contributors PRs, we should have at least some basics test like:
- Make sure `ember-cli-storybook` build
- Try it with an example repo
- something else?

**Comment by gabrielcsapo** [comment]
We should also ensure we move to GitHub-actions to make adding code easier. Have we thought about migrating this package to the main storybook repo? It is required by the ember framework integration, it would be easier to have both of them collocated.

**Comment by gabrielcsapo** [comment]
https://github.com/storybookjs/ember-cli-storybook/commit/b32f8dfa2793ae52b578e7ad79ad97c90b234a28 adds GitHub Actions support so we should be able to add tests and get feedback in PRs again. Travis support was dropped rather abruptly.

**Comment by gabrielcsapo** [comment]
This should be solved with the linked issue.
