### ISSUE TITLE
outputReady hook not working correctly

### ISSUE THREAD

**Issue by peabnuts123** [storybookjs/ember-cli-storybook#8]
When running this addon in my (large, old, sophisticated) app the `outputReady` hook is not functioning correct and cannot generate the config files necessary for this to work.

The following section of code:
```js
outputReady: function() {
  if (!this.app) {
    // You will need ember-cli >= 1.13 to use ember-cli-deploy's postBuild integration.
    // This is because prior to 1.13, `this.app` is not available in the outputReady hook.
    this.ui.writeLine('please upgrade to ember-cli >= 1.13')
    return;
  }
…
```

`this.app` is undefined for some reason, despite being on Ember and Ember-CLI 3.8. If I create a new project it works okay (though the app still does not run properly…). I don't know enough about ember-cli and addons to know whether or not it's expected behaviour for `this.app` to be undefined under some scenarios or if my project is misconfigured somehow. Any ideas?

```
$ ember --version
ember-cli: 3.8.1
node: 10.15.1
os: darwin x64
```

**Comment by gabrielcsapo** [comment]
This should have been fixed in https://github.com/storybookjs/ember-cli-storybook/commit/37cf3a2a57a303b6a6094a1db4f32150d5ed23b9

**Comment by peabnuts123** [comment]
What prompted you to look up the resolution to this issue? 😅

**Comment by gabrielcsapo** [comment]
I was the original creator of this addon and of the ember support for storybook. I have been trying to get resourcing to have LinkedIn start using this more internally and seeing all the movement from the community I am hoping I can start contributing more again!
