### ISSUE TITLE
Missing/incomplete documentation

### ISSUE THREAD

**Issue by fpauser** [storybookjs/ember-cli-storybook#88]
https://storybook.js.org/addons/@storybook/ember-cli-storybook and https://github.com/storybookjs/ember-cli-storybook/blob/master/README.md are incomplete and do not properly explain how to install/run ember-cli-storybook
a) in an ember app
b) in an ember addon

**Comment by gabrielcsapo** [comment]
There shouldn't be additional work to get it working in an app or addon. Running `ember install` should do everything needed. Are you finding issues with the current docs?
